name: Python CI

on:
  push:
    branches: [ main, lara2 ]
  pull_request:
    branches: [ main, lara2 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pipenv virtualenv
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/virtualenvs
          .venv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies from Pipfile.lock
      run: pipenv sync --python ${{ matrix.python-version }}

    - name: Run tests
      run: pipenv run pytest

    - name: Run example script
      run: pipenv run python example.py