name: Python CI

on:
  push:
    branches: [ main, lara ]
  pull_request:
    branches: [ main, lara ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: [3.8]

    - name: Cache pipenv virtualenv
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/share/virtualenvs
          .venv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Run pytest
      run: |
        pipenv run pytest tests/test_math_randomseed.py
